run_name: test_data
output_dir: "../v2-results"
raw_fastq_path: #00-data/fastq/ #path to raw fastq files 
trimmed_fastq_path: #trimmed files must have suffix _R[1,2].fastq.gz
sample_manifest_file: 00-data/manifest_pe.csv # if provided and trimming, then import to raw_fastq.qza, then trim into a new trimmed_fastq.qza. 
#if provided and not trimming, just import to fastq.qza

to_trim: True #Boolean
paired_end: True

amplicon_name: ssu16sv4v5 #not currently used
# trimming parameters
fwd_primer: GTGYCAGCMGCCGCGGTAA
rev_primer: GGACTACNVGGGTWTCTAAT
discard_untrimmed: False
minimum_length: 50
trimming_threads: 4
#quality parameters
seq_quality_cutoff: 0.85 # not used  yet
