site_name: Tourmaline Docs
theme:
  name: readthedocs
  highlightjs: true
#extra_css: [style_2.css]
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
nav:
  - 'Home': 'index.md'
  - 'Install and Setup': 'install.md'
  - 'Configuration': 'configuration.md'
  - 'Running': 'running.md'
  - 'Steps':
    - 'QA/QC': 'steps/qaqc.md'
    - 'Repseqs (ASV Generation)': 'steps/repseqs.md'
    - 'Taxonomy': 'steps/taxonomy.md'
  - 'External Data': 'external_data.md'
  - 'Metadata': 'metadata.md'
  - 'Troubleshooting': 'troubleshooting.md'
  - 'Citation & Legacy': 'citation_legacy.md'
use_directory_urls: false
