run_name: test_mifish_pe_man
# marker_info:  marker_info.yaml

# SAMPLE STEP: Preparing sequence files for denoising, saves to [run_name]-samples folder
raw_fastq_path: /Users/katherine.silliman/Projects/NOAA/tourmaline-dev/v2-tourmaline/test-fastqs
trimmed_fastq_path: 
#sample_manifest_file: manifest_pe.csv
sample_metadata_file: metadata.csv # optional if no summary plotting
# trimming 
to_trim: TRUE #Boolean
paired_end: True
amplicon_name: 12S-MiFish
fwd_primer: GCCGGTAAAACTCGTGCCAGC
rev_primer: CATAGTGGGGTATCTAATCCCAGTTTG
trim_params: "--discard-untrimmed -m 50"
trimming_threads: 1
seq_quality_cutoff: 0.85

# ASV STEP: Denoising and clustering, saves to [run_name]-repseqs folder
asv_method: # dada2pe, dada2se, deblur

# TAXA STEP: Assigning taxonomy, saves to [run_name]-taxonomy folder
# run_name-repseqs default source, or make this a shell command param
database_path:
database_name: # change if not same as file name
taxonomy_ranks:
assignment_method:


# ADDITIONAL PARAMS

# Outputs
biom: #Boolean
qiime_artifacts: #Boolean
tsvs: #Boolean
# ASV METHODS
# DADA2 PAIRED-END
# For more info run: qiime dada2 denoise-paired --help

dada2pe_trunc_len_f: 240
dada2pe_trunc_len_r: 190
dada2pe_trim_left_f: 0
dada2pe_trim_left_r: 0
dada2pe_max_ee_f: 2
dada2pe_max_ee_r: 2
dada2pe_trunc_q: 2
dada2pe_pooling_method: independent
dada2pe_chimera_method: consensus
dada2pe_min_fold_parent_over_abundance: 1
dada2pe_n_reads_learn: 1000000
dada2pe_hashed_feature_ids: --p-hashed-feature-ids

# DADA2 SINGLE-END
# For more info run: qiime dada2 denoise-single --help

dada2se_trunc_len: 240
dada2se_trim_left: 0
dada2se_max_ee: 2
dada2se_trunc_q: 2
dada2se_pooling_method: independent
dada2se_chimera_method: consensus
dada2se_min_fold_parent_over_abundance: 1
dada2se_n_reads_learn: 1000000
dada2se_hashed_feature_ids: --p-hashed-feature-ids

# DEBLUR SINGLE-END
# For more info run: qiime deblur denoise-other --help

deblur_trim_length: 240
deblur_sample_stats: --p-sample-stats
deblur_mean_error: 0.005
deblur_indel_prob: 0.01
deblur_indel_max: 3
deblur_min_reads: 10
deblur_min_size: 2
deblur_hashed_feature_ids: --p-hashed-feature-ids

# Assignment methods
assignment_params:

# Sample filtering


